# Seeds from:
# http://www.random.org/sequences/?min=-4999&max=5000&col=1&format=plain&rnd=date.2014-01-27
all:
	# Circle center:
	# http://www.random.org/decimal-fractions/?num=20&dec=5&col=2&format=plain&rnd=date.2014-03-11
	./circle.py -n     10000 --cx 0.86596 --cy 0.46907 --radius 100 --seed  4910
	./circle.py -n     10000 --cx 0.98023 --cy 0.84319 --radius   1 --seed -2210
	./circle.py -n    100000 --cx 0.68995 --cy 0.28915 --radius 100 --seed -2225
	./circle.py -n    100000 --cx 0.22034 --cy 0.10309 --radius   1 --seed     0
	./circle.py -n   1000000 --cx 0.18526 --cy 0.73156 --radius 100 --seed -4735
	./circle.py -n   1000000 --cx 0.60610 --cy 0.73914 --radius   1 --seed  2612
	./circle.py -n  10000000 --cx 0.78515 --cy 0.24104 --radius 100 --seed -1921
	./circle.py -n  10000000 --cx 0.04491 --cy 0.65631 --radius   1 --seed  4944
	./circle.py -n 100000000 --cx 0.11681 --cy 0.64900 --radius 100 --seed  3200
	./circle.py -n 100000000 --cx 0.51899 --cy 0.43621 --radius   1 --seed  4671
	# Lines:
	./lines.py  -n     10000 -l 100 --scale 100 --seed -3107
	./lines.py  -n     10000 -l   3 --scale 100 --seed  -991
	./lines.py  -n    100000 -l 100 --scale 100 --seed  2648
	./lines.py  -n    100000 -l   3 --scale 100 --seed  3201
	./lines.py  -n   1000000 -l 100 --scale 100 --seed  4445
	./lines.py  -n   1000000 -l   3 --scale 100 --seed   976
	./lines.py  -n  10000000 -l 100 --scale 100 --seed -4983
	./lines.py  -n  10000000 -l   3 --scale 100 --seed -3516
	./lines.py  -n 100000000 -l 100 --scale 100 --seed -2397
	./lines.py  -n 100000000 -l   3 --scale 100 --seed  2921
	# Curve xmin xmax:
	# http://www.random.org/integers/?num=10&min=-4999&max=5000&col=2&base=10&format=plain&rnd=date.2014-08-05
	./curve.py  -n     10000 --xmin -3793 --xmax -2238 --seed  3685
	./curve.py  -n     10000 --xmin    -1 --xmax     1 --seed  3968
	./curve.py  -n    100000 --xmin -2654 --xmax  4420 --seed  4677
	./curve.py  -n    100000 --xmin    -1 --xmax     1 --seed  3646
	./curve.py  -n   1000000 --xmin -3394 --xmax   940 --seed  1272
	./curve.py  -n   1000000 --xmin    -1 --xmax     1 --seed -2726
	./curve.py  -n  10000000 --xmin -3699 --xmax  3558 --seed  4361
	./curve.py  -n  10000000 --xmin    -1 --xmax     1 --seed -1072
	./curve.py  -n 100000000 --xmin  2887 --xmax  3653 --seed  -807
	./curve.py  -n 100000000 --xmin    -1 --xmax     1 --seed -1580
	# Square xmin xmax ymin xmax:
	# http://www.random.org/integers/?num=20&min=-4999&max=5000&col=4&base=10&format=plain&rnd=date.2014-09-19
	./square.py  -n     10000 --xmin -4917 --xmax  1169 --ymin -2864 --ymax  1100 --seed  4439
	./square.py  -n     10000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed  4027
	./square.py  -n    100000 --xmin -3600 --xmax -2009 --ymin -1753 --ymax  1354 --seed  2918
	./square.py  -n    100000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed   744
	./square.py  -n   1000000 --xmin -4840 --xmax   263 --ymin -2101 --ymax  1042 --seed   510
	./square.py  -n   1000000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed   715
	./square.py  -n  10000000 --xmin  1736 --xmax  3733 --ymin  -951 --ymax  2544 --seed -1240
	./square.py  -n  10000000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed  -888
	./square.py  -n 100000000 --xmin  3438 --xmax  4361 --ymin -3839 --ymax  3863 --seed  1646
	./square.py  -n 100000000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed   184	
	# Triangle xmin xmax ymin xmax:
	# http://www.random.org/integers/?num=20&min=-4999&max=5000&col=4&base=10&format=plain&rnd=date.2014-05-07
	./triangle.py  -n     10000 --xmin   842 --xmax  3457 --ymin -3129 --ymax  3750 --seed -1726
	./triangle.py  -n     10000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed   374
	./triangle.py  -n    100000 --xmin  1775 --xmax  2639 --ymin -1863 --ymax  1364 --seed -3838
	./triangle.py  -n    100000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed  -859
	./triangle.py  -n   1000000 --xmin   950 --xmax  1885 --ymin -3713 --ymax  -132 --seed -2886
	./triangle.py  -n   1000000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed -2024
	./triangle.py  -n  10000000 --xmin -2747 --xmax -2412 --ymin  1797 --ymax  4482 --seed -1903
	./triangle.py  -n  10000000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed  2288
	./triangle.py  -n 100000000 --xmin -2504 --xmax  4562 --ymin  2247 --ymax  4629 --seed -3599
	./triangle.py  -n 100000000 --xmin    -1 --xmax     1 --ymin    -1 --ymax     1 --seed -4484
